In [8]:
import pandas as pd
import numpy as np

### Считываем нашу таблицу

In [9]:
PATH = 'Dataset_of_places.csv'
N = 30 #Количество перемножений

In [10]:
df = pd.read_csv(PATH)
df 

Place  412б  НГУ  209м  душ
0  412б     0    7    29    0
1   НГУ     3    0    11    0
2  209м    31    7     0    5
3   душ     1    0     4    0

### Перевод в матрицу

In [11]:
matrix = df.drop('Place', axis=1)
matrix = matrix.to_numpy(dtype = float)
print(matrix)


[[ 0.  7. 29.  0.]
 [ 3.  0. 11.  0.]
 [31.  7.  0.  5.]
 [ 1.  0.  4.  0.]]


### Делаем нормировку, высчитывая количество транзитов в каждой строке

In [12]:
n = [np.sum(matrix[i]) for i in range(len(matrix))]

for i in range(len(n)):
    matrix[i] = matrix[i]/n[i]

### "Обучаем"

In [13]:
for i in range(N):
    matrix = np.dot(matrix, matrix)
matrix *=100

### Результат

In [14]:
result = pd.DataFrame(data=matrix, columns=['412б','НГУ','209м','душ'])
result.head()

412б        НГУ       209м       душ
0  36.129418  14.260036  44.442779  5.167765
1  36.129418  14.260036  44.442779  5.167765
2  36.129418  14.260036  44.442779  5.167765
3  36.129418  14.260036  44.442779  5.167765

### Таким образом, мы получили вероятности посетить каждое место